spring:
  datasource:
    url: jdbc:h2:mem:testdb
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true 
  h2:
    console:
      enabled: true
   
ntt:
  kakfa:
    topicName: productEventBus